# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.cache/wt [current_project]
set_property parent.project_path C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/Adder_Substractor.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/D_FF.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/Decoder_2_to_4.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/Decoder_3_to_8.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/FA.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/HA.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/new/Ins_Decoder.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/new/Logical_Unit_4B.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/Multiplexer.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/new/Multiplier_4.vhd
  {C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/5-Way 4-Bit MUX/Mux_5W_4B.vhd}
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/Mux_8_to_1.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/Mux_8way_4bit.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/new/Program_ROM.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/Reg.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/new/Reg_Bank.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/new/Seven_Segment.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/new/Slow_Clock.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/T_bit_Adder.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nano_processor_improved/comparator.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nanoprocessor-Design/p_counter.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/imports/Nano_processor_improved/shifter_4B.vhd
  C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/sources_1/new/Nano_Processor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/constrs_1/imports/Nano_processor_improved/Basys3Labs.xdc
set_property used_in_implementation false [get_files C:/Users/SAMPR/Downloads/Nano_processor_improved_DNG/Nano_processor_improved/Nano_processor_improved/Nano_processor_improved.srcs/constrs_1/imports/Nano_processor_improved/Basys3Labs.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Nano_Processor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nano_Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Nano_Processor_utilization_synth.rpt -pb Nano_Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
